version: "3.3"
services:
        web:
                image: nginx:latest
                container_name: mynginx
                ports: 
                        - "80:80"
                volumes:
                        - ./www:/var/www/html
                        - ./src/nginx.ini:/etc/nginx/conf.d/default.conf
                        - ./src/php-fpm.conf:/etc/php/7.4/fpm/php-fpm.conf
                        - ./src/www.conf:/etc/php/7.4/fpm/pool.d/www.conf
                depends_on:
                        - php
                networks:
                        - app-network
        php:
                build: './src/php'                
                container_name: myphp
                ports: 
                        - "9000:9000"
                volumes:
                        - ./www:/var/www/html
                depends_on:
                        - mysql
                networks:
                        - app-network
        phpmyadmin:
                image: phpmyadmin/phpmyadmin
                container_name: phpmyadmin
                ports:
                        - '8080:80'
                environment:
                        PMA_HOST: mysql
                depends_on:
                        - mysql
                networks:
                        - app-network
        mysql:
                image: mariadb:latest
                container_name: mysql
                ports:
                        - "3306:3306"
                environment:
                        - MYSQL_ROOT_PASSWORD=MyDBRoot123
                        - MYSQL_DATABASE=project
                        - MYSQL_USER=php
                        - MYSQL_PASSWORD=php
                networks:
                        - app-network
networks:
        app-network:
                driver: bridge
